kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo:     henrynicolas/mailserver
    custom_dns: 192.168.11.66
    username: 
      from_secret: HUB_USERNAME
    password: 
      from_secret: HUB_PASSWORD
    tags:
      - latest
